import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const outputDefault = resolve(root, "worker-configuration.d.ts");

function canonicalizeGeneratedTypes(source) {
  return source
    .replace(
      /^\/\/ Generated by Wrangler by running `[^`]+` \(hash: ([^)]+)\)$/m,
      "// Generated by Wrangler by running `wrangler types` (hash: $1)",
    )
    .replace(
      /\r?\n\tinterface GlobalProps \{\r?\n\t\tmainModule: typeof import\("[^"]+"\);\r?\n\t\}\r?\n/,
      "\n",
    );
}

function valueAfter(argv, name, fallback) {
  const index = argv.indexOf(name);
  return index >= 0 ? argv[index + 1] : fallback;
}

export async function runWranglerTypes(argv = process.argv.slice(2)) {
  const mode = argv[0] ?? "generate";
  if (!["generate", "check"].includes(mode))
    throw new Error(
      "Usage: node scripts/wrangler-types.mjs <generate|check> [--output <path>]",
    );

  const output = resolve(valueAfter(argv, "--output", outputDefault));
  const config = valueAfter(argv, "--config");
  const logRoot = await mkdtemp(join(tmpdir(), "branduel-wrangler-logs-"));
  const generatedRoot = await mkdtemp(
    join(tmpdir(), "branduel-wrangler-types-"),
  );
  const generatedOutput = join(generatedRoot, "worker-configuration.d.ts");
  const outputArgument = relative(root, generatedOutput) || ".";
  const wrangler = resolve(
    root,
    "node_modules",
    "wrangler",
    "bin",
    "wrangler.js",
  );
  const args = [wrangler, "types", outputArgument];
  if (config) args.push("--config", resolve(config));

  try {
    const result = spawnSync(process.execPath, args, {
      cwd: root,
      env: {
        ...process.env,
        CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV: "false",
        WRANGLER_LOG_PATH: logRoot,
      },
      stdio: "inherit",
      shell: false,
    });
    if (result.error) throw result.error;
    if ((result.status ?? 1) !== 0) return result.status ?? 1;

    const generated = canonicalizeGeneratedTypes(
      await readFile(generatedOutput, "utf8"),
    );
    if (mode === "generate") {
      await writeFile(output, generated, "utf8");
      return 0;
    }

    let existing;
    try {
      existing = canonicalizeGeneratedTypes(await readFile(output, "utf8"));
    } catch {
      existing = null;
    }
    if (existing === generated) {
      console.log(`Types at ${output} are up to date.`);
      return 0;
    }
    console.error(
      `Types at ${output} are out of date. Run \`wrangler types\` to regenerate.`,
    );
    return 1;
  } finally {
    await rm(logRoot, {
      recursive: true,
      force: true,
      maxRetries: 3,
      retryDelay: 50,
    });
    await rm(generatedRoot, {
      recursive: true,
      force: true,
      maxRetries: 3,
      retryDelay: 50,
    });
  }
}

if (process.argv[1]?.endsWith("wrangler-types.mjs")) {
  try {
    process.exitCode = await runWranglerTypes();
  } catch (error) {
    console.error(
      error instanceof Error
        ? error.message
        : "Wrangler type generation failed.",
    );
    process.exitCode = 1;
  }
}
